# Generated by Django 5.2.7 on 2025-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('newsletter', 'Newsletter'), ('offer', 'Offer'), ('notification', 'Notification'), ('quote', 'Quote'), ('confirmation', 'Confirmation'), ('alert', 'Alert')], default='alert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
