# Generated by Django 5.2.7 on 2025-11-15 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('newsletter', 'Newsletter'), ('offer', 'Offer'), ('notification', 'Notification'), ('quote', 'Quote'), ('confirmation', 'Confirmation'), ('alert', 'Alert')], default='alert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
